### ISSUE TITLE
我下载了该库，研究之后发现内存快照搜索路径有问题

### ISSUE THREAD

**Issue by StubbornSlug** [yaukeywang/LuaMemorySnapshotDump#2]
我觉的现在类似深搜的这种搜索出来的路径，很难分析  应该按照广搜 或者优先搜索thread与function之外的对象，之后再搜thread和function及只有他们引用的upvalues，这样引用路径会清爽很多而便于分析，我的代码改的比较粗暴只在这里说一下思路代码就不上传了

**Comment by yaukeywang** [comment]
Hi，这个工具的重点不是直接单看某一份快照所有的内容，实在太多了很难看出什么；目的是要使用对比的接口，来对比同一个地方的两个不同时间点的快照，查看增量是否合理，否则单看一份快照的内容，首先不能确定是否有内存泄露，而且也很难找到泄露的地方。
不过谢谢你的提议，我会再思考下改进的地方。

**Comment by yaukeywang** [comment]
ps: 如果可以，请顺便给一个 Star 吧  : ) Thanks

**Comment by StubbornSlug** [comment]
Star已给，工具正需要，感谢分享

**Comment by yaukeywang** [comment]
Hi，我强烈推荐你用上述的方式试试：同一个地方，不同时间点的快照对比（自带的对比方法），来分析增长点，具体我在相关中文博客有写，之前我的项目就是这样排除掉lua端内存泄漏，希望对你有帮助。

**Comment by StubbornSlug** [comment]
嗯，现在就是用快照对比在查找，文档都看过了，很详细，帮助很大，万分感谢
